exclude: ["README.md", "Rakefile"]
highlighter: pygments
relative_permalinks: true
markdown: kramdown

title : The Growth Blog
author :
  name : David Kim
  email : daviddarden11@gmail.com
  github : dklounge
  twitter : findinbay
  feedburner : techproductmanager

production_url : http://techproductmanager.com

BASE_PATH : false
ASSET_PATH : false

sharing :
  provider : false

analytics :
  provider : google
  google :
      tracking_id : 'UA-43170427-2'
  getclicky :
    site_id :

comments:
  provider : disqus
  disqus:
    short_name: dklounge
