exclude: ["README.md", "Rakefile"]
pygments: true
relative_permalinks: true

title : David Kim homepage
author :
  name : David Kim
  email : daviddarden11@gmail.com
  github : dklounge
  twitter : findinbay
  feedburner : DavidKimBlog

production_url : http://dklounge.github.io

BASE_PATH : false
ASSET_PATH : false

sharing :
  provider : false

analytics :
  provider : google
  google :
      tracking_id : 'UA-43170427-2'
  getclicky :
    site_id :

comments:
  provider : disqus
  disqus:
    short_name: dklounge
